project_id = "rcwepnqjyowlbtmltwxo"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.notify-validation]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.weekly-admin-report]
    verify_jwt = true
  [functions.weekly-digest]
    verify_jwt = true
  [functions.digest-landing]
    verify_jwt = true
